# Generated by Django 5.2.5 on 2025-10-04 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0002_remove_car_id_remove_customer_id_remove_sale_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='average',
        ),
        migrations.RemoveField(
            model_name='car',
            name='car_id',
        ),
        migrations.RemoveField(
            model_name='car',
            name='fuel_type',
        ),
        migrations.RemoveField(
            model_name='car',
            name='km_run',
        ),
        migrations.RemoveField(
            model_name='car',
            name='model',
        ),
        migrations.RemoveField(
            model_name='car',
            name='register_year',
        ),
        migrations.RemoveField(
            model_name='car',
            name='status',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='sale_id',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='total_price',
        ),
        migrations.AddField(
            model_name='car',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='car',
            name='name',
            field=models.CharField(default='Unknown Car', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='customer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='sale',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(default='cars/default_car.jpg', upload_to='cars/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(default='Unknown Customer', max_length=100),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
