# Generated by Django 5.2.5 on 2025-10-04 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0006_alter_car_id_alter_customer_id_alter_sale_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='average',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(default='Petrol', max_length=50),
        ),
        migrations.AddField(
            model_name='car',
            name='km_run',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.CharField(default='Standard Model', max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='register_year',
            field=models.IntegerField(default=2020),
        ),
        migrations.AddField(
            model_name='car',
            name='status',
            field=models.CharField(default='Available', max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='total_price',
            field=models.FloatField(default=0.0),
        ),
    ]
